/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "i2c1_driver.h"
#include "bme280.h"

volatile int32_t g_temp_centiC = 0;
volatile uint32_t g_pressure_pa = 0;
volatile uint32_t g_humidity_permille = 0;


int main(void)
{
	BME280_Data reading;
	i2c1Init();

	if(!bme280Init())
	{
		// Initialization failed - spin here. In real code replace with an LED blink pattern or an error log in real code
		while(1)
		{
			// trapped - BME280 not found/responding
		}
	}

	while(1)
	{

	}
}
